# Generated by Django 3.0.4 on 2020-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='in_stock',
            field=models.BooleanField(),
        ),
    ]
